Document: scribe
Title: Debian scribe Manual
Author: <insert document author here>
Abstract: This manual describes what scribe is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scribe/scribe.sgml.gz

Format: postscript
Files: /usr/share/doc/scribe/scribe.ps.gz

Format: text
Files: /usr/share/doc/scribe/scribe.text.gz

Format: HTML
Index: /usr/share/doc/scribe/html/index.html
Files: /usr/share/doc/scribe/html/*.html
